const keys = [
  { name:"" ,item: "ا", value: 1 },
  { name:"" ,item: "ب", value: 2 },
  { name:"" ,item: "ت", value: 4 },
  { name:"" ,item: "ة", value: 4 },
  { name:"" ,item: "ث", value: 5 },
  { name:"" ,item: "ج", value: 3 },
  { name:"" ,item: "ح", value: 8 },
  { name:"" ,item: "خ", value: 6 },
  { name:"" ,item: "د", value: 4 },
  { name:"" ,item: "ذ", value: 7 },
  { name:"" ,item: "ر", value: 2 },
  { name:"" ,item: "ز", value: 7 },
  { name:"" ,item: "س", value: 6 },
  { name:"" ,item: "ش", value: 3 },
  { name:"" ,item: "ص", value: 9 },
  { name:"" ,item: "ض", value: 8 },
  { name:"" ,item: "ط", value: 9 },
  { name:"" ,item: "ظ", value: 9 },
  { name:"" ,item: "ع", value: 7 },
  { name:"" ,item: "غ", value: 1 },
  { name:"" ,item: "ف", value: 8 },
  { name:"" ,item: "ق", value: 1 },
  { name:"" ,item: "ك", value: 2 },
  { name:"" ,item: "ل", value: 3 },
  { name:"" ,item: "م", value: 4 },
  { name:"" ,item: "ن", value: 5 },
  { name:"" ,item: "ه", value: 5 },
  { name:"" ,item: "و", value: 6 },
  { name:"" ,item: "ي", value: 1 },
  { name:"space" ,item: " ", value: 0 },
 
];

export default keys;
